### ISSUE TITLE
problems with Mac OS Catalina

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/dsc-mongodb#4]
With Mac OS Catalina, the root folder is no longer writeable, so 
    sudo mkdir -p /data/db
    sudo chown -R `id -un` /data/db
are both obsolete now.

https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/

**Comment by lindseyberlin** [comment]
" "Catalina" doesn't allow users to install in root directory, so when installing Mongo, it tries to install in root and fails. Solution is to create a directory in a different location manually and then go and install MongoDB " - solution from other online instructor

**Comment by lindseyberlin** [comment]
Link from Rafael elaborating on my previous comment: https://medium.com/@bryantjiminson/fixing-data-db-not-found-error-in-macos-x-when-starting-mongodb-d7b82abb2479

**Comment by christine-egan42** [comment]
This issue is being consolidated into this issue: https://github.com/learn-co-curriculum/dsc-mongodb-lab/issues/4
