### ISSUE TITLE
MongoDB, can't set up databae

### ISSUE THREAD

**Issue by Zeth-Abney** [learn-co-curriculum/dsc-mongodb#5]
## Link to Canvas

https://learning.flatironschool.com/courses/4679/assignments/162327?module_item_id=347722
https://learning.flatironschool.com/courses/4679/quizzes/25717?module_item_id=347725

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [X ] Instructions unclear
- [ X] Other (explain below)
-    explained above. 

### Source

```
Next, we have to create a directory to store our Mongo data files:

sudo mkdir -p /data/db

Give the directory the correct permission:

sudo chown -R `id -un` /data/db
```

### Concern

![image](https://user-images.githubusercontent.com/74474624/147864222-d2a3f48e-470e-4c33-9e87-ddf3e1b4756f.png)
![image](https://user-images.githubusercontent.com/74474624/147864225-6e939d0f-1f0c-4256-8fd9-439b2b465163.png)

## (Optional) Proposed Solution

include terminal commands for windows and macOS as well... mention at least once topics that will be asked about during the quiz. 

## What OS Are You Using?

- [ ] OS X
- [ X] Windows (11) 
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

## Any Additional Context?

My Cohort leader told me that since we won't be using MongoDB nearly at all, it is not really worth worrying about and to just move on to the next module/lesson; according to him, MongoDB is notoriously temperamental anyway. Which is fair I suppose, but I'm paying a lot of money for this program and this makes me feel like I am not getting the full value that I'm paying for.

**Comment by christine-egan42** [comment]
This issue is being consolidated into this issue: https://github.com/learn-co-curriculum/dsc-mongodb-lab/issues/4
