### ISSUE TITLE
Instructions to install mongo doesn't work on Windows 

### ISSUE THREAD

**Issue by sanderlin2013** [learn-co-curriculum/dsc-mongodb#6]
The instructions for how to install MongoDB doesn't work on my windows computer, even when switching between the command prompt and Git Bash. 

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by christine-egan42** [comment]
This issue is being consolidated into this issue: https://github.com/learn-co-curriculum/dsc-mongodb-lab/issues/4
